// this is the root layout, you can change fontFamily globally here.

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/components/Navbar";

const outfit = localFont({
  src: "../public/fonts/Outfit-Regular.ttf",
  variable: "--font-outfit",
});

const ArchiaBold = localFont({
  src: "../public/fonts/archia-bold-webfont.woff2",
  variable: "--font-archia-bold",
});

export const metadata: Metadata = {
  title: "Mohammad S.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = [
    {
      name: "Home",
      link: "/",
    },
    {
      name: "About",
      link: "/about",
    },
    {
      name: "Experience",
      link: "/experience",
    },
    {
      name: "Projects",
      link: "/project",
    },
  ];

  return (
    <html lang="en">
      <body className={`${outfit.variable} ${ArchiaBold.variable}`}>
        <Navbar
          title="Mohammad Sahrullah."
          frontLogo="./image/Ms-solid.png"
          backLogo="./image/me-small.png"
          data={menu}
        />
        <div className="container mx-auto ">{children}</div>
      </body>
    </html>
  );
}
